services:
  server:
    env_file:
      - ./.env.docker
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
  db:
    env_file:
      - ./.env.docker
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
