services:
  server:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      - POSTGRES_PASSWORD
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/music_center?schema=public
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
